[diff_pdf]
build = "docker compose --profile mermaid run --build --rm mermaid_diagrams && docker compose --profile python run --build --rm python_diagrams && docker compose --profile latex run --build --rm latex"
env_file = ".env"
pdf_from_target = true
view = true

[diff_pdf.env]
PYTHONIOENCODING = "utf-8"
PYTHONUTF8 = "1"
VAULT_PATH = { from_env = "VAULT_PATH" }
VAULT_OS_PATH = { from_env = "VAULT_OS_PATH", resolve = true }

[diff_pdf.copy]
paths = [
    ".env",
    "docker-compose.yaml",
    "docker/mermaid.dockerfile",
    "docker/latex.dockerfile",
    "титульник.pdf",
    "задание.pdf",
    "scripts/build_all.py",
    "scripts/convert_docx_to_pdf.py",
    "scripts/build_latex_docker.py",
]
