services:
  latex:
    build: .
    volumes:
      - ./:/data
      - ${VAULT_OS_PATH}:${VAULT_PATH}
    working_dir: /data
    command: sh -c "latexmk -lualatex -interaction=nonstopmode ${TARGET} && latexmk -c"
    env_file:
      - ./.env