version: '3'

dotenv:
  - .env

vars:
  COMPOSE_BUILD_PROFILES: --profile docx --profile mermaid --profile python --profile latex --profile crop
  COMPOSE_ALL_PROFILES: --profile docx --profile mermaid --profile python --profile latex

includes:
  build:
    taskfile: ./tasks/build.yml
    flatten: true
  diagrams:
    taskfile: ./tasks/diagrams.yml
    flatten: true
  docker:
    taskfile: ./tasks/docker.yml
    flatten: true
  docs:
    taskfile: ./tasks/docs.yml
    flatten: true
  docx:
    taskfile: ./tasks/docx.yml
    flatten: true
  latex:
    taskfile: ./tasks/latex.yml
    flatten: true
  python:
    taskfile: ./tasks/python.yml
    flatten: true
  tools:
    taskfile: ./tasks/tools.yml
    flatten: true

tasks:
  default:
    desc: Показать доступные задачи
    cmds:
      - task --list
