[project]
site_name = "Документация проекта диплома"
site_author = "Artyom Kupriianov"
docs_dir = "docs"
site_dir = "docs-site"
dev_addr = "0.0.0.0:8000"
repo_url = "https://github.com/ethercod3/diploma_latex"
repo_name = "Репозиторий"
nav = [
  {"Введение" = "README.md"},
  {"Структура проекта" = "project-structure.md"},
  {"Быстрый старт" = "quick-start.md"},
  {"Сборка без Docker" = "manual-build.md"},
  {"Настройка TeXstudio" = "texstudio.md"},
  {"Docker" = "docker.md"},
  {"Документация" = "zensical.md"},
  {"Сравнение PDF между коммитами" = "pdf-diff.md"},
  {"Проблемы с компиляцией" = "troubleshooting.md"},
  {"Титульник и задание" = "title-pages.md"},
  {"Код в приложениях" = "source-code.md"},
  {"Диаграммы" = "diagrams.md"},
  {"Git hooks" = "git-hooks.md"}
]

[project.theme]
language = "ru"
features = [
  "content.tabs.link",
  "content.code.copy"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.zensical.extensions.macros]
module_name = "docs_macros"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]


[[project.extra.social]]
icon = "fontawesome/brands/telegram"
link = "https://t.me/eth3ria1"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ethercod3"