version: '3'

tasks:
  mermaid:
    desc: Сгенерировать Mermaid-диаграммы локально
    cmds:
      - mmdc {{.CLI_ARGS}}

  mermaid:docker:
    desc: Сгенерировать Mermaid-диаграммы в Docker
    cmds:
      - docker compose --profile mermaid run --build --rm mermaid_diagrams mmdc {{.CLI_ARGS}}

  diagrams:
    desc: Сгенерировать Python-диаграммы локально
    cmds:
      - uv run python scripts/compile_python_diagrams.py

  diagrams:docker:
    desc: Сгенерировать Python-диаграммы в Docker
    cmds:
      - docker compose --profile python run --build --rm python_diagrams
