version: '3'

tasks:
  python:lint:
    desc: Проверить форматирование Python-файлов через Black
    cmds:
      - python -m black --check --diff scripts python_diagrams docs

  python:format:
    desc: Отформатировать Python-файлы через Black
    cmds:
      - python -m black scripts python_diagrams docs
