version: '3'

tasks:
  python:lint:
    desc: Проверить форматирование Python-файлов через Black
    cmds:
      - uv run black --check --diff scripts python_diagrams docs tests

  python:format:
    desc: Отформатировать Python-файлы через Black
    cmds:
      - uv run black scripts python_diagrams docs tests

  python:test:
    desc: Запустить Python-тесты
    cmds:
      - uv run pytest
