services:
  mermaid_diagrams:
    build:
      context: ../
      dockerfile: ./docker/mermaid.dockerfile
    env_file:
      - ../.env
    volumes:
      - ../figures:/data/figures
    command: ["python3", "compile_mermaid.py"]
